### ISSUE TITLE
'ProfileGenericObject' object has no attribute 'value'

### ISSUE THREAD

**Issue by markg85** [psy0rz/p1_dsmr_to_influxdb#1]
Hi,

Well, the title says it all :)
'ProfileGenericObject' object has no attribute 'value'

Or to give more information:
```Waiting for P1 port measurement..
'ProfileGenericObject' object has no attribute 'value'
Pausing and restarting...
Connecting db
Waiting for P1 port measurement..
'ProfileGenericObject' object has no attribute 'value'
Pausing and restarting...
Connecting db
Waiting for P1 port measurement..
'ProfileGenericObject' object has no attribute 'value'
Pausing and restarting...
Connecting db
```

Did i perhaps miss something?
I installed the libraries you depend on.
The config is listening on /dev/ttyUSB0 which seems to be my P1 to USB cable as it's gone when not plugged in.

I didn't do any serial monitoring just yet as the dump you see above is about 10 seconds per `ProfileGenericObject` line which seems about right for P1.

One thing that might matter is that i do have a smart meter but i don't have gas.

Cheers,
Mark

**Comment by johnvanweel** [comment]
I had the same issue, created a pull request that fixes this.

**Comment by psy0rz** [comment]
Sorry i forgot to respond to this issue. @johnvanweel thanks for fixing it!

**Comment by markg85** [comment]
I'll close this one then.
Thank you for making the patch @johnvanweel and for @psy0rz for applying it :)

**Comment by johnvanweel** [comment]
No problem, thank you for the scripts!

**Comment by psy0rz** [comment]
Please like and subscribe ;)
