### ISSUE TITLE
Q: JSON geeft ander dashboard dan live preview

### ISSUE THREAD

**Issue by tomsteenbakkers** [psy0rz/p1_dsmr_to_influxdb#4]
Ik heb de code aan het werk en ook het dashboard. Ik zie alleen dat jouw live dashboard anders is dan de JSON in de GitHub.

Kun jij jouw Dashboard JSON delen. Wil namelijk ook mijn opbrengsten zien.

**Comment by tomsteenbakkers** [comment]
Ik zag dat je met de share optie toch de JSON kan kopiëren, dus ik heb nu de laatste versie van je dashboard. Blijft er 1 vraag over. Soms laat hij dat wel zien maar overall waar meter ID in de query staat wordt geen data getoond. 

Ik zie ook in de query dat je een tabel gebruik die Meter values heet. Dit heb ik echter niet.

Enig idee hoe dit kan?

**Comment by psy0rz** [comment]
Dat klopt, ik heb een apparte KWH meter per groep.

Om die meters uit te lezen heb ik dit gemaakt: https://github.com/psy0rz/YTLmodbus
